export const ORDER_ADD_REQUEST = "ORDER_ADD_REQUEST";
export const ORDER_ADD_SUCCESS = "ORDER_ADD_SUCCESS";
export const ORDER_ADD_FAIL = "ORDER_ADD_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_CHANGE_STATE_REQUEST = "ORDER_CHANGE_STATE_REQUEST";
export const ORDER_CHANGE_STATE_SUCCESS = "ORDER_CHANGE_STATE_SUCCESS";
export const ORDER_CHANGE_STATE_FAIL = "ORDER_CHANGE_STATE_FAIL";
